
// if you're using pannel carefully edit this part.

const sessionName = 'session';
const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUhEMDdCRFNEY2pyU1FQSVI1Y2pzaVdVZEgvYklsZ1hGUHhTT1pQRUttbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSkRmWUNvZEVkYk5teG5DK1BvSEJOV2NaRUVoOVhKYzM1elcwNjdGMVcxbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRRVBzYzJyL3c3QUVJUWNNVnB0bHFKTGdlMHQ0a24vZFJQSFNIMnk2N1cwPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI3K2E1dEtHOXdnckRNUVlFQWhuUFVIeFB5ZTR1SUR6Ly9oMzVHUVZIRGlBPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im9LUmp4YlI5cnlSZnNFWUVQcnh6NHByN2lHWnRNU0ZjZVZHNG5DTld0SEE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlFkV0FtUWRLQ1pQNWtnbnVucFdseDE2K2ZMaXJXdUc5bkhCQU4xTEpYV1E9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT09jTDhJSEZkZndoT3ZRa01jNytzUVFpZ0VsTFU2WjQvVlBZUTNBVlVsRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTkQ1cW1EaDR3d3VEZFo5WXNiNng4TkIzYk9CaEVLWDNOc0tvZ01UWXFqMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1JVzJYTm43bStQeVZTekNqeG5hKy9EaW9VSVhFYXVXaTFMcUE2cnFGNVl1bE1NK2dtSjdVL1BCS2laZGJscDJwdTAwaUhPbEFvQjhic2VDM0RYdWdnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NDIsImFkdlNlY3JldEtleSI6Im16OCtCRnJTcDdrMUg0M3kwdDJRaFBCRVBlOU9uTjNRNGs5UTJUUFBOU0E9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzA0MDA5Njc3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjVDRkJENjFCODY2OTFBN0Q4MEE1MjE4RTY0RkYwOENDIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTMzOTI4Njd9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDcwNDAwOTY3N0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI4RUU4RDFDNEJCOURDQkFCNDcyQzM5NzZGMDE4NkU0NSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUzMzkyODg3fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJEWkQ5SEtSViIsIm1lIjp7ImlkIjoiMjU0NzA0MDA5Njc3OjE2QHMud2hhdHNhcHAubmV0IiwibGlkIjoiMzEzODgyMjQ5OTk0NjE6MTZAbGlkIiwibmFtZSI6Ik1zbmFwZHJhZ29uIOKdpO+4j/CfqbgifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ01QcTBzUURFTkxOaXNRR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IjBmL2xWODZPYkMzWUF6eWhvWUZaRHhBekkzSjlETW1ldGdRK1R1c0ViRkE9IiwiYWNjb3VudFNpZ25hdHVyZSI6IlRYbTYxbnBmWUw5YjJJeUNjYmZNVHJGU3VXSzU4M1QvMkJpQTdnVzJpVlRMcHFLZnNkajE5SVBkS1NMY2tkQTQ5NS9KRWRleitrVmdoZlJQcTZuVEJBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJOVmpyVEdUUU9YN0lnU1RjSXJuZURIV0dKblBqRCtOZThXVDI2YnNYSUVPZkw1UldkcXhhZ216RzBWK3Z4SHVmQ3pjR0JMK1FrRm90VWhGbEdLUWVqdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDcwNDAwOTY3NzoxNkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJkSC81VmZPam13dDJBTThvYUdCV1E4UU15TnlmUXpKbnJZRVBrN3JCR3hRIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQklJQlE9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NTMzOTI4NjMsImxhc3RQcm9wSGFzaCI6IlBXazVCIiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFNR0sifQ==';
const appname = process.env.APP_NAME || '';
const herokuapi = process.env.HEROKU_API;
const botname = process.env.BOTNAME || '𝗥𝗔𝗩𝗘𝗡-𝗕𝗢𝗧';
const author = process.env.STICKER_AUTHOR || '𝗕𝗢𝗧';
const packname = process.env.STICKER_PACKNAME || '𝗥𝗔𝗩𝗘𝗡';
const dev = process.env.DEV || '254114660061';
const owner = dev.split(",");
const menulink = process.env.MENU_LINK || 'https://files.catbox.moe/duv8ac.jpg';
const menu = process.env.MENU_TYPE || 'VIDEO';
const bad = process.env.BAD_WORD || 'fuck';
const admin = process.env.ADMIN_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗿𝗲𝘀𝗲𝗿𝘃𝗲𝗱 𝗳𝗼𝗿 𝗔𝗱𝗺𝗶𝗻𝘀!';
const group = process.env.GROUP_ONLY_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝗚𝗿𝗼𝘂𝗽𝘀!';
const botAdmin = process.env.BOT_ADMIN_MSG || '𝗜 𝗻𝗲𝗲𝗱 𝗔𝗱𝗺𝗶𝗻 𝗽𝗿𝗲𝘃𝗶𝗹𝗲𝗱𝗴𝗲𝘀!';
const NotOwner = process.env.NOT_OWNER_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝘁𝗵𝗲 𝗼𝘄𝗻𝗲𝗿!';
const mycode = process.env.CODE || '254';
const port = process.env.PORT || 8080;
const databaseUrl = process.env.DATABASE_URL || '';

module.exports = {
  session,
  sessionName,
  author,
  packname,
  dev,
  owner,
  bad,
  group,
  NotOwner,
  botname,
  botAdmin, 
  menu,
  menulink,
  admin,
  mycode,
  herokuapi,
  port,
  appname,
  databaseUrl
};
